import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./themeProvider";
import Nav from "./nav/Nav";
import Footer from "./footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tolu's Portofolio App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
 
        <body
          className={` bg-slate-100 dark:bg-[#121212] text-black dark:text-white ${inter.className}`}>
          <ThemeProvider>
            <main>{children}</main>
          </ThemeProvider>
        </body>
    </html>
  );
}
